# Generated by Django 4.2.13 on 2026-04-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='idempotency_merchan_16ab98_idx',
            old_name='idempotency_merchant_8c8f90_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_491d5c_idx',
            old_name='ledger_entr_merchan_0dbf08_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrequest',
            new_name='payout_requ_merchan_8737ee_idx',
            old_name='payout_requ_merchan_6f8a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrequest',
            new_name='payout_requ_status_1899f6_idx',
            old_name='payout_requ_status_807387_idx',
        ),
    ]
