# Generated by Django 4.2.13 on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "payouts",
            "0002_rename_idempotency_merchant_8c8f90_idx_idempotency_merchan_16ab98_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoint",
                        to="payouts.merchant",
                    ),
                ),
            ],
            options={"db_table": "webhook_endpoints"},
        ),
    ]

