# Generated by Django 4.2.13 on 2026-04-25 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_rename_idempotency_merchant_8c8f90_idx_idempotency_merchan_16ab98_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='payouts.merchant')),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED_RETRY', 'FailedRetry'), ('FAILED_PERMANENT', 'FailedPermanent')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payouts.webhookendpoint')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payouts.merchant')),
            ],
            options={
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['delivery_status', 'next_attempt_at'], name='webhook_eve_deliver_8fbeb9_idx'), models.Index(fields=['merchant', 'created_at'], name='webhook_eve_merchan_0109ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payouts.merchant')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='audit_logs_merchan_87fe31_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
    ]
