# Generated by Cursor on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0003_webhookendpoint"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        # PayoutAuditLog (table may already exist in some DBs)
                        """
                        CREATE TABLE IF NOT EXISTS payout_audit_logs (
                            id BIGSERIAL PRIMARY KEY,
                            merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE NO ACTION,
                            actor_type VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                            actor_id VARCHAR(255) NULL,
                            action VARCHAR(255) NOT NULL,
                            resource_type VARCHAR(255) NOT NULL,
                            resource_id VARCHAR(255) NOT NULL,
                            metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                        );
                        """,
                        "CREATE INDEX IF NOT EXISTS payout_audi_merchan_50c6c1_idx ON payout_audit_logs (merchant_id, created_at);",
                        "CREATE INDEX IF NOT EXISTS payout_audi_resourc_3e6a83_idx ON payout_audit_logs (resource_type, resource_id);",
                        # WebhookEvent (table may already exist in some DBs)
                        """
                        CREATE TABLE IF NOT EXISTS webhook_events (
                            id UUID PRIMARY KEY,
                            merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE NO ACTION,
                            event_type VARCHAR(50) NOT NULL,
                            payload JSONB NOT NULL,
                            delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                            attempt_count INTEGER NOT NULL DEFAULT 0,
                            next_attempt_at TIMESTAMPTZ NULL,
                            last_error TEXT NULL,
                            idempotency_key VARCHAR(255) NOT NULL UNIQUE,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                        );
                        """,
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PayoutAuditLog",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("actor_type", models.CharField(default="SYSTEM", max_length=50)),
                        ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                        ("action", models.CharField(max_length=255)),
                        ("resource_type", models.CharField(max_length=255)),
                        ("resource_id", models.CharField(max_length=255)),
                        ("metadata", models.JSONField(blank=True, default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "merchant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="audit_logs",
                                to="payouts.merchant",
                            ),
                        ),
                    ],
                    options={"db_table": "payout_audit_logs"},
                ),
                migrations.AddIndex(
                    model_name="payoutauditlog",
                    index=models.Index(
                        fields=["merchant", "created_at"],
                        name="payout_audi_merchan_50c6c1_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="payoutauditlog",
                    index=models.Index(
                        fields=["resource_type", "resource_id"],
                        name="payout_audi_resourc_3e6a83_idx",
                    ),
                ),
                migrations.CreateModel(
                    name="WebhookEvent",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("event_type", models.CharField(max_length=50)),
                        ("payload", models.JSONField()),
                        (
                            "delivery_status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("DELIVERED", "Delivered"),
                                    ("FAILED", "Failed"),
                                    ("FAILED_PERMANENT", "Failed (Permanent)"),
                                ],
                                default="PENDING",
                                max_length=20,
                            ),
                        ),
                        ("attempt_count", models.IntegerField(default=0)),
                        ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                        ("last_error", models.TextField(blank=True, null=True)),
                        ("idempotency_key", models.CharField(max_length=255, unique=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "merchant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="webhook_events",
                                to="payouts.merchant",
                            ),
                        ),
                    ],
                    options={"db_table": "webhook_events"},
                ),
            ],
        )
    ]

