# Generated by Django 4.2.13 on 2026-04-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_webhookevent_payoutauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payoutauditlog',
            new_name='payout_audi_merchan_10c38b_idx',
            old_name='payout_audi_merchan_50c6c1_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutauditlog',
            new_name='payout_audi_resourc_1b4fe9_idx',
            old_name='payout_audi_resourc_3e6a83_idx',
        ),
    ]
